### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by cqx931** [shadoof/rtwtr#10]
- [x] Animation: TIdy up Javascript parameters

- Parsers
- [x] Proper space handling for `<tb>` parsing (move Cayley's preprocessing)
- [ ] Handle `<unit>` defined within sentences.
- [ ] Parse `<unit>` inline

- Environment
- [x] Remove files that are not in use. 
- [ ] Configure Yarn/npm command for git diff & running server
- [ ] Set up netlify[on hold for now]
